### ISSUE TITLE
"You may need an appropriate loader to handle this file type" -errors after switching from react-scripts

### ISSUE THREAD

**Issue by turbolego** [Sean-Bradley/R3F-Pack#3]
Hi!

Thanks for making this alternative to react-scripts! 😄 

I have several errors in regards to .svg and .jpg files after switching:

> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

My webpack.config.js file has rules for both .svg and .jpg files, and using either url-loader or file-loader results in the same error.

Is this an issue related to switching from react-scripts or something else?

**Comment by Sean-Bradley** [comment]
I haven't implemented those, since its easier to just place your static assets in the public folder.
Example : https://github.com/Sean-Bradley/React-Three-Fiber-Boilerplate/tree/obstacleCourse

Anyway,
I made a change so that you can at least do something like this in your `./src/*.jsx` files,
```javascript
import logo from './logo.png';

function App() {
  return <img src={logo} />
}
```

To get latest version (v2.6.0)
```bash
npm install r3f-pack@latest --save-dev
```
